name: 'Get dependencies'
description: 'Workflow to get dependencies'

runs:
  using: 'composite'
  steps:
    - name: Running pub get
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 60
        max_attempts: 2
        retry_on: error
        command: ${{ inputs.command || 'melos pub_get_changes' }}
