name: lego

packages:
  - app/**
  - feature/**

x-ignores:
  &build_yaml_files_ignores [ example ]

command:
  bootstrap:
    environment:
      sdk: ^3.4.3
      flutter: ^3.22.2

    dependencies:
      flutter_bloc: 8.1.3
      freezed_annotation: 2.4.1
      intl: 0.19.0
      i69n: 2.1.0
      injectable: 2.3.2
      json_annotation: 4.8.1
      retrofit: 4.0.3
      meta: 1.12.0

    dev_dependencies:
      bdd_widget_test: 1.7.2
      build_runner: 2.4.6
      freezed: 2.4.5
      injectable_generator: 2.4.1
      json_serializable: 6.7.1
      mocktail: 1.0.3
      retrofit_generator: 8.0.2

scripts:
  test:
    run: melos run test:unit_test
    description: Run all tests in this project

  pub_get_changes:
    run: |
      melos exec --fail-fast --diff=origin/main...HEAD --include-dependents -- flutter pub get --suppress-analytics
    description: Run `flutter pub get` in all changed packages with dependents.
  pub_get_changes_no_dependents:
    run: |
      melos exec --fail-fast --diff=origin/main...HEAD -- flutter pub get --suppress-analytics
    description: Run `flutter pub get` in all changed packages.
