name: 'Initial Workflow'
description: 'Initial workflow to prepare the env'

inputs:
  flutter_channel:
    required: false
    description: 'Flutter channel'
    default: "stable"
  flutter_version:
    required: false
    description: 'Flutter version'
    default: 3.22.2

runs:
  using: 'composite'
  steps:
    - name: '🐦 Setup Flutter'
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{inputs.flutter_version}}
        channel: ${{inputs.flutter_channel}}
        cache: true

    - name: '📦 Install Dependencies'
      run: |
        flutter config --no-analytics
        dart pub global activate melos
      shell: bash
