name: Update Coverage for Main

on:
  push:
    branches:
      - main

jobs:
  update_coverage:
    runs-on: ubuntu-latest

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3

      - name: Get PR number from merge commit
        id: pr
        run: |
          PR_NUMBER=$(gh pr list --state merged --json number --jq '.[0].number')
          echo "PR_NUMBER=${PR_NUMBER}" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download run-id artifact from PR
        id: download_run_id
        run: |
          RUN_ID=$(gh run list --branch=main --event=pull_request --json databaseId --jq '.[0].databaseId')
          echo "RUN_ID=${RUN_ID}" >> $GITHUB_ENV

      - name: Download coverage artifact from PR
        uses: actions/download-artifact@v4
        with:
          name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ env.RUN_ID }}
          path: coverage_report

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
